services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -p ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    logging:
      driver: "none"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    logging:
      driver: "none"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    logging:
      driver: "none"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level critical

  worker:
    build:
      context: ./backend
    command: celery -A app.worker:celery worker --loglevel=critical --logfile=/dev/null
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - backend
      - redis
    logging:
      driver: "none"

  scheduler:
    build:
      context: ./backend
    command: celery -A app.worker:celery beat --loglevel=critical --logfile=/dev/null
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - backend
      - redis
    logging:
      driver: "none"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    logging:
      driver: "none"

volumes:
  postgres_data:
  redis_data: