version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: statuspage
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    env_file: ./backend/.env
    command: celery -A app.worker worker --loglevel=info
    depends_on:
      - db
      - redis

  beat:
    build: ./backend
    env_file: ./backend/.env
    command: celery -A app.worker beat --loglevel=info
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
