services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: statuspage
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "55432:55432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://Admin:Password@db:5432/statuspage
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend
    command: celery -A app.worker:celery worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://Admin:Password@db:5432/statuspage
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key
    depends_on:
      - backend
      - redis

  scheduler:
    build:
      context: ./backend
    command: celery -A app.worker:celery beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://Admin:Password@db:5432/statuspage
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
      - "3000:443"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
