apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "status-page.fullname" . }}
  labels:
    {{- include "status-page.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "status-page.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "status-page.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "status-page.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: "{{ .Values.database.endpoint }}"  # RDS endpoint
            - name: DB_PORT
              value: "5432"  # Default PostgreSQL port
            - name: DB_NAME
              value: "status-page"  # Database name
            - name: DB_USER
              value: "status-page"  # Username
            - name: DB_PASSWORD
              value: "{{ .Values.database.password }}"  # Directly reference the password
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.djangoSecretKey }}"
          ports:
            - containerPort: 8000
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: {{ .Values.livenessProbe.httpGet.path }}*/}}
{{/*              port: {{ .Values.livenessProbe.httpGet.port }}*/}}
{{/*            initialDelaySeconds: 15*/}}
{{/*            periodSeconds: 20*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: {{ .Values.readinessProbe.httpGet.path }}*/}}
{{/*              port: {{ .Values.readinessProbe.httpGet.port }}*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            periodSeconds: 10*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}